version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: motorbike-backend-${NODE_ENV:-production}
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/motorbike
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - motorbike-network

  mongodb:
    image: mongo:latest
    container_name: mongodb-${NODE_ENV:-production}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - motorbike-network

volumes:
  mongodb_data:
    name: mongodb_data_${NODE_ENV:-production}

networks:
  motorbike-network:
    name: motorbike-network-${NODE_ENV:-production}
    driver: bridge